name: Swift Android SDK Smoke Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-spm:
    runs-on: windows-latest
    name: Build ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, aarch64 ]
        api-level: [ 29 ]
        host-tag: [ windows-x86_64 ]

    steps:
      - name: Checkout cassowary project
        uses: actions/checkout@v4
        with:
          repository: compnerd/cassowary
          path: ${{ github.workspace }}/SourceCache/cassowary

      - uses: compnerd/gha-setup-vsdevenv@main

      - uses: compnerd/gha-setup-swift@main
        with:
          github-repo: thebrowsercompany/swift-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-asset-name: installer-amd64.exe
          release-tag-name: "20250115.2"

      - uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410 # v1.5.0
        id: setup-ndk
        with:
          ndk-version: r26d
          local-cache: true

      - name: Setup Swift environment
        id: android-swift-env
        run: |
          echo "sysroot=$(resolve-path ${{ steps.setup-ndk.outputs.ndk-path }}\toolchains\llvm\prebuilt\${{ matrix.host-tag }}\sysroot)" >> $env:GITHUB_OUTPUT
          echo "sdkroot=$(resolve-path $env:SDKROOT\..\..\..\..\Android.platform\Developer\SDKs\Android.sdk)" >> $env:GITHUB_OUTPUT
          echo "xctestroot=$(resolve-path $env:SDKROOT\..\..\..\..\Android.platform\Developer\Library\XCTest-development)" >> $env:GITHUB_OUTPUT
          echo "clang-resource-dir=$(& $(resolve-path "${{ steps.setup-ndk.outputs.ndk-path }}\toolchains\llvm\prebuilt\${{ matrix.host-tag }}\bin\clang.exe") -print-resource-dir)" >> $env:GITHUB_OUTPUT

      - name: Print Swift environment
        run: |
          echo "sysroot:${{ steps.android-swift-env.outputs.sysroot }}"
          echo "sdkroot:${{ steps.android-swift-env.outputs.sdkroot }}"
          echo "xctestroot:${{ steps.android-swift-env.outputs.xctestroot }}"
          echo "clang-resource-dir:${{ steps.android-swift-env.outputs.clang-resource-dir }}"

      - name: Build cassowary project
        run: |
          swift build `
            --package-path ${{ github.workspace }}/SourceCache/cassowary `
            --triple ${{ matrix.arch }}-unknown-linux-android${{ matrix.api-level }} `
            --sdk "${{ steps.android-swift-env.outputs.sysroot }}" `
            -Xswiftc -sdk -Xswiftc "${{ steps.android-swift-env.outputs.sdkroot }}" `
            -Xswiftc -sysroot -Xswiftc "${{ steps.android-swift-env.outputs.sysroot }}" `
            -Xswiftc -I -Xswiftc "${{ steps.android-swift-env.outputs.sdkroot }}\usr\include" `
            -Xswiftc -Xclang-linker -Xswiftc -resource-dir -Xswiftc -Xclang-linker -Xswiftc ${{ steps.android-swift-env.outputs.clang-resource-dir }} `
            -Xswiftc -I -Xswiftc "${{ steps.android-swift-env.outputs.xctestroot }}\usr\lib\swift\android" `
            -Xlinker "-L${{ steps.android-swift-env.outputs.xctestroot }}\usr\lib\swift\android\${{ matrix.arch }}"
